function tono = notaviolin(A, tecla, dur, fs)

f = 440 * (2^((tecla-49)/12));
t = 0:1/fs:dur;vibrato = 7;
tono = ...
    A * (sin(2*pi*t*vibrato)+5)/6 ...
    .*(1.8*sin(pi*t/(dur))) ...
    .*(0.6* ...
       (sin(2*pi*f*t) ...
       +sin(2*pi*f*t*2)/4 ...
       +sin(2*pi*f*t*3)/4 ...
       +sin(2*pi*f*t*4)/4 ...
       +sin(2*pi*f*t*5)/5 ...
       +sin(2*pi*f*t*6)/6 ...
       +sin(2*pi*f*t*7)/7 ...
       +sin(2*pi*f*t*8)/8 ...
       +sin(2*pi*f*t*9)/9 ...
       +sin(2*pi*f*t*10)/10 ...
       ));

end